language: php

php:
  - 5.4

services:
  - rabbitmq

before_script:
  - composer selfupdate
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

notifications:
  email: matthiasnoback@gmail.com
